### ISSUE TITLE
Issue with `spawn` on Windows

### ISSUE THREAD

**Issue by unindented** [tirsen/retry-cli#5]
It looks like using `spawn` on Windows is causing `retry-cli` to exit with status zero before the command is actually run.

I tried replacing your use of `spawn` with the `cross-spawn` package, and the issue went away. @tirsen 
 would you be open to merge a PR that fixes this issue?

**Comment by tirsen** [comment]
Definitely. If you send a PR I will merge it!

**Comment by unindented** [comment]
@tirsen awesome! Here you go: https://github.com/tirsen/retry-cli/pull/6
